### ISSUE TITLE
Takes over 100% CPU

### ISSUE THREAD

**Issue by soroushhakami** [gavoja/aemsync#13] opened 2015-08-28 10:59 UTC
Hi, and thanks for this awesome library.

The only problem I have is that when starting it up, on my OSX 10 machine it instantly takes 100%+ CPU: 

Any idea what could be the reason?

**Comment by willtonkin** [comment] 2015-09-21 17:11
Have you tried running it with a Node.js profiler?

**Comment by hedefalk** [comment] 2015-10-12 11:23
+1 140% CPU :)

**Comment by hedefalk** [comment] 2015-10-12 15:34
I profiled for a few seconds with node-inspector:

<img width="1273" alt="screen shot 2015-10-12 at 17 33 07" src="https://cloud.githubusercontent.com/assets/116520/10431797/6b438b16-7107-11e5-8669-959417eae706.png">

**Comment by gavoja** [comment] 2015-10-12 15:37
Hi guys,

Thanks for reporting this. It looks like an issue with chokidar which AEMSync uses for watching over file system changes. On OS X it is supposed to use fsevents by default and results in a high CPU utilisation otherwise (as it uses polling) - can you please verify this is indeed the case? More on that here:
https://www.npmjs.com/package/chokidar#performance

I don't currently have access to a Mac, which seems to be only OS affected and I would appreciate any help.

Cheers,
Michal

**Comment by hedefalk** [comment] 2015-10-12 15:48
@gavoja Thanks for looking into it!

I'm sorry, but my first profile screenshot was bad. I was running from an incorrect folder and therefore no work was being done (it wasn't really using much CPU in this case). Here is a screenshot when running with actual 130-140 % CPU:

<img width="1240" alt="screen shot 2015-10-12 at 17 45 58" src="https://cloud.githubusercontent.com/assets/116520/10432062/220a32fe-7109-11e5-8907-b4ea6fe6064a.png">

Doesn't seem to be saying much though… Any tips on profiling tools? I used node-inspector and just "node-debug aemsync.js" here.

**Comment by gavoja** [comment] 2015-10-12 15:58
Could you please try the following:

1. Verify if `fsevents` is installed in `aemsync/node_modules/chokidar/node_modules` - in the location where you have AEMSync installed.
2. Try adding `useFsEvents: true` argument to `chokidar.watch` call (line 492).

**Comment by willtonkin** [comment] 2015-10-12 16:00
As @gavoja mentions, this is detailed as a known issue in chokidar.

I'm on a mac but I'm not seeing this issue, so can't recreate.

Also, you could confirm this suspected issue by disabling fs polling:
```
--- a/aemsync.js
+++ b/aemsync.js
@@ -491,7 +491,8 @@ function Watcher(pathToWatch, queue, userFilter, callback) {
                // Start watcher.
                var watcher = chokidar.watch(pathsToWatch, {
                        ignored: ignored,
-                       persistent: true
+                       persistent: true,
+                       usePolling: false
                });

                // When scan is complete.
```

This should hopefully resolve the issue in this instance as per the suggestion here: https://github.com/paulmillr/chokidar#performance

**Comment by hedefalk** [comment] 2015-10-12 16:07
@gavoja 

1. No, it's not: 
<img width="211" alt="screen shot 2015-10-12 at 18 00 25" src="https://cloud.githubusercontent.com/assets/116520/10432403/282483ae-710b-11e5-9b40-215254d23128.png">

2. Added that argument but ~140% CPU remains

**Comment by hedefalk** [comment] 2015-10-12 16:13
@willtonkin With this change it dies:

```
Scanning for 'jcr_root/*' folders ...
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: watch ENFILE
    at exports._errnoException (util.js:837:11)
    at FSWatcher.start (fs.js:1237:11)
    at Object.fs.watch (fs.js:1263:11)
    at createFsWatchInstance (/Users/viktor/dev/sj/workspaces/aem/projects/common-ui/buildsupport/node_modules/aemsync/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/Users/viktor/dev/sj/workspaces/aem/projects/common-ui/buildsupport/node_modules/aemsync/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at EventEmitter.NodeFsHandler._watchWithNodeFs (/Users/viktor/dev/sj/workspaces/aem/projects/common-ui/buildsupport/node_modules/aemsync/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at EventEmitter.NodeFsHandler._handleFile (/Users/viktor/dev/sj/workspaces/aem/projects/common-ui/buildsupport/node_modules/aemsync/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at EventEmitter.<anonymous> (/Users/viktor/dev/sj/workspaces/aem/projects/common-ui/buildsupport/node_modules/aemsync/node_modules/chokidar/lib/nodefs-handler.js:468:21)
    at FSReqWrap.oncomplete (fs.js:82:15)
```

**Comment by hedefalk** [comment] 2015-10-13 07:27
Isn't it pretty strange that usePolling gives throws an exception when it states here https://github.com/paulmillr/chokidar#performance that this is the default already… I've turned it on and off a few times now and it consistently blows up with above exception if I have `usePolling: true` but not otherwise.

**Comment by willtonkin** [comment] 2015-10-13 07:43
Very strange, I've been trying to recreate your situation on my Mac with no luck. I can enable/disable polling and all seems well.

**Comment by hedefalk** [comment] 2015-10-13 08:02
Oh, I _think_ my problem was I had problems with node-gyp which made fsevents not being installed but not failing build because it was optional. To solve this I needed to update from xcode 6 to xcode 7 for the command line tools which made node-gyp work again. So I just `rm -r node_modules` on our main project now and then `npm install` and now chokidar actually installed fssync. And now I can't even see any node process in top :)

**Comment by willtonkin** [comment] 2015-10-13 08:09
😊 awesome! Nice job

**Comment by hedefalk** [comment] 2015-10-13 08:18
For reference: https://github.com/nodejs/node-gyp/issues/734#issuecomment-147435222

**Comment by hedefalk** [comment] 2015-10-13 12:57
I have confirmed with a colleague that that making sure node-gyp works so that fsevents is installed under chokidar makes the CPU hog go away. I guess fsevents is optional for chokidar but shouldn't really be optional for osx. I suggest you can close this issue! Thanks!

**Comment by gavoja** [comment] 2015-10-13 13:25
Thanks for looking into it!

**Closed** 2015-10-13 13:25 UTC
